#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

sudo pacman -S --needed nginx

cp "$BASEDIR/nginx.conf" /etc/nginx/nginx.conf

sudo systemctl enable --now nginx